### ISSUE TITLE
data from database

### ISSUE THREAD

**Issue by paoslaos** [Valdes-Tresanco-MS/NbThermo#1]
Dear authors,

congratulations on your manuscript and fabulous web page. Can you advise me how to proceed and download the data shown at https://valdes-tresanco-ms.github.io/NbThermo/ to my personal computer please?

Sincerely,
P.

**Comment by Valdes-Tresanco-MS** [comment]
Sure. This is the file:
https://github.com/Valdes-Tresanco-MS/NbThermo/blob/master/src/app/dashboard/data/database.json

This file is composed of a list of dictionaries containing every Nb information. For example

```json
[
  {
    "id": "00001",
    "Info": {
        "Name": {"value": "NRL-N-C2", "notes": null},
        "Reference": {"DOI": "https://pubs.acs.org/doi/10.1021/acs.analchem.1c00677", 
        "Date": null},
        "Annotation": {"Last update": null, "Changes": null}},
    "Tm": {
        "nanoDSF": {"value": null, "notes": null},
        "DSF (SYPRO)": {"value": null, "notes": null},
        "DSC": {"value": null, "notes": null},
        "Other": {"value": null, "notes": null},
        "Circular dichroism": {"value": 67.5, "notes": null},
        "Refolding (%)": {"value": 63, "notes": null}},
    "Binding": {
        "Antigen1": {"name": "SARS-CoV-2 nucleocapsid (N)", "type": "protein", "affinity": 1.1, "notes": null},
        "Antigen2": {"name": null, "type": null, "affinity": null, "notes": null},
        "Antigen3": {"name": null, "type": null, "affinity": null, "notes": null},
        "Antigen4": {"name": null, "type": null, "affinity": null, "notes": null}},
    "Yield (mg/L)": {
        "Periplasm": {"value": 14, "notes": null},
        "Cytoplasm": {"value": null, "notes": null},
        "Other": {"value": null, "notes": null}
    },
    "Origin": {
        "Source": {"value": "Llama"},
        "Type": {"value": "Natural"},
        "Obtaining method": {"value": "immunization", "notes": null}}
}
]
```

You can read this file easily with Python and the standard json lib. 
I have to make some improvements and update it with the latest data, but I am currently in Cuba and the internet is bad, besides having restricted access to many magazines and articles.
Let me know if I can help you with anything else.
Mario S.

**Comment by paoslaos** [comment]
Thank you. Apologies for missing the already available resource.

Sincerely,
P.

**Comment by Valdes-Tresanco-MS** [comment]
Don't worry. I'm happy to help you.
Soon, I will configure the page to be able to download this data.
Best!
Mario S.
